language: c++
compiler: gcc
dist: trusty

addons:
  apt:
    packages:
    - e2fsprogs
    - uuid
    - uuid-dev
    - gnome-common
    - libparted-dev
    - libgtkmm-3.0-dev
    - libdevmapper-dev
    - gnome-doc-utils
    - docbook-xml

git:
  depth: 1

branches:
  only:
    - gparted-gtk3-github

script:
 - ./autogen.sh
 - make
